"""Ground truth for the policy-search comparison: a service as a PA request might describe it, and the
title pattern of the coverage policy that should come back. Two phrasings per service: formal and plain.
A policy counts as right if its title matches the pattern (local policies repeat across regions, so several can match)."""
SERVICES = [
    ("icd", r"implantable cardioverter defibrillator", "implantation of a transvenous implantable cardioverter defibrillator for primary prevention in heart failure", "ICD for a heart failure patient with low ejection fraction"),
    ("bariatric", r"bariatric surgery", "laparoscopic Roux-en-Y gastric bypass for morbid obesity with type 2 diabetes", "weight loss surgery gastric bypass BMI 42"),
    ("cpap", r"continuous positive airway pressure", "CPAP device for obstructive sleep apnea with apnea hypopnea index of 22", "CPAP machine for sleep apnea"),
    ("home_o2", r"home use of oxygen", "home oxygen therapy for chronic hypoxemia with arterial oxygen saturation below 88 percent", "oxygen tank at home for COPD patient"),
    ("ldct", r"lung cancer screening", "annual low dose computed tomography screening for a 66 year old with 30 pack-year smoking history", "lung CT screening for a long-time smoker"),
    ("pet", r"positron emission tomography \(fdg\) for oncologic", "FDG PET scan for initial treatment strategy in newly diagnosed lung cancer", "PET scan to stage cancer"),
    ("cochlear", r"cochlear implant", "unilateral cochlear implantation for bilateral severe sensorineural hearing loss", "cochlear implant for deafness"),
    ("tavr", r"transcatheter aortic valve", "transcatheter aortic valve replacement for severe symptomatic aortic stenosis", "TAVR for a heart valve that is too narrow"),
    ("pacemaker", r"cardiac pacemakers", "dual chamber permanent pacemaker implantation for symptomatic sick sinus syndrome", "pacemaker for slow heart rate"),
    ("vad", r"ventricular assist devices", "left ventricular assist device as destination therapy for end-stage heart failure", "heart pump LVAD for advanced heart failure"),
    ("heart_tx", r"heart transplant", "orthotopic heart transplantation for refractory cardiomyopathy", "heart transplant"),
    ("lvrs", r"lung volume reduction", "lung volume reduction surgery for severe upper lobe emphysema", "surgery to shrink lungs in emphysema"),
    ("hbot", r"hyperbaric oxygen", "hyperbaric oxygen therapy for a non-healing diabetic foot ulcer", "pressure chamber oxygen treatment for wound"),
    ("bmd", r"bone \(mineral\) density|bone mass measurement|bone density", "dual energy x-ray absorptiometry bone density scan for postmenopausal osteoporosis", "DEXA bone density test"),
    ("sleep_test", r"sleep testing", "attended polysomnography for suspected obstructive sleep apnea", "overnight sleep study"),
    ("vns", r"vagus nerve stimulation", "vagus nerve stimulator implantation for treatment-resistant depression", "VNS implant for depression"),
    ("dbs", r"deep brain stimulation", "deep brain stimulation for Parkinson disease with motor fluctuations", "brain pacemaker for tremor"),
    ("liver_tx", r"liver transplant", "liver transplantation for decompensated cirrhosis", "liver transplant"),
    ("stem_cell", r"stem cell transplantation", "allogeneic hematopoietic stem cell transplantation for acute myeloid leukemia", "bone marrow transplant for leukemia"),
    ("cart", r"chimeric antigen receptor", "CAR T-cell therapy for relapsed large B-cell lymphoma", "CAR-T cancer treatment"),
    ("laac", r"left atrial appendage", "percutaneous left atrial appendage closure for atrial fibrillation in a patient who cannot take anticoagulants", "Watchman device"),
    ("teer", r"transcatheter edge-to-edge repair|mitral valve", "transcatheter edge-to-edge repair for severe mitral regurgitation", "MitraClip for leaky mitral valve"),
    ("sci", r"spinal cord stimulat", "spinal cord stimulator implantation for failed back surgery syndrome", "back pain nerve stimulator implant"),
    ("esi", r"epidural steroid injection", "lumbar transforaminal epidural steroid injection for radiculopathy", "steroid shot in the spine for sciatica"),
    ("facet", r"facet joint", "medial branch block and radiofrequency ablation for lumbar facet joint pain", "injection for facet joint back pain"),
    ("si_joint", r"sacroiliac", "sacroiliac joint injection for sacroiliitis", "SI joint pain injection"),
    ("varicose", r"varicose vein", "endovenous radiofrequency ablation of the great saphenous vein for symptomatic varicose veins", "vein ablation for leg varicose veins"),
    ("blepharoplasty", r"blepharoplasty", "upper eyelid blepharoplasty for visual field obstruction from dermatochalasis", "eyelid surgery for droopy lids"),
    ("hospital_bed", r"hospital beds", "semi-electric hospital bed for a bedbound patient with pressure ulcers", "hospital bed for home use"),
    ("power_chair", r"power mobility|wheelchair", "power wheelchair for a patient with severe mobility limitation", "motorized wheelchair"),
    ("glucose", r"glucose monitor", "continuous glucose monitor for insulin-treated type 1 diabetes", "CGM sensor for diabetes"),
    ("proton", r"proton beam", "proton beam radiation therapy for a skull base chordoma", "proton therapy for cancer"),
    ("cataract", r"cataract", "cataract extraction with intraocular lens implantation for visual acuity 20/70", "cataract surgery"),
    ("botox", r"botulinum toxin", "onabotulinumtoxinA injections for chronic migraine prophylaxis", "Botox for migraines"),
    ("npwt", r"negative pressure wound", "negative pressure wound therapy pump for a stage 4 sacral pressure ulcer", "wound vac"),
    ("tens", r"transcutaneous electrical nerve stimulation|electrical nerve stimulation", "transcutaneous electrical nerve stimulation unit for chronic low back pain", "TENS unit for back pain"),
    ("mri", r"magnetic resonance imaging", "MRI of the brain in a patient with an implanted pacemaker", "MRI scan with a pacemaker"),
    ("tms", r"transcranial magnetic stimulation", "repetitive transcranial magnetic stimulation for major depressive disorder after failed antidepressants", "TMS for depression"),
    ("pulm_rehab", r"pulmonary rehabilitation", "pulmonary rehabilitation program for severe COPD", "lung rehab for COPD"),
    ("pta", r"percutaneous transluminal angioplasty", "carotid artery stenting for symptomatic stenosis in a high surgical risk patient", "stent in the neck artery"),
    ("lumbar_fusion", r"lumbar spinal fusion", "open lumbar spinal fusion L4-L5 for spondylolisthesis with instability", "back fusion surgery for slipped vertebra"),
    ("cervical_fusion", r"cervical", "anterior cervical discectomy and fusion for cervical radiculopathy", "neck fusion surgery for pinched nerve"),
    ("dialysis", r"dialysis|esrd|end stage renal", "home hemodialysis for end-stage renal disease", "dialysis at home"),
    ("ventilator", r"ventilator|respiratory assist", "home mechanical ventilator for chronic respiratory failure", "breathing machine at home"),
]
